server:
  port: 8761
spring:
  application:
    name: eval-eureka-server
eureka:
  instance:
     hostname: ${spring.cloud.client.ip-address}
     prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    #### 清理间隔（单位毫秒，默认是60*1000），开发环境设置如下可快速移除不可用的服务
    eviction-interval-timer-in-ms: 60000
    enable-self-preservation: false
